spring:
  datasource:
    url: jdbc:mysql://47.93.53.45:3306/chatroom?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 3MB
  rabbitmq:
    host: 47.93.53.45
    port: 5672
    username: admin
    password: password
    virtual-host: /
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090
